# comment added for pipeline test
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: mtuben
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/mtuben-harbor-project/app@sha256:5c4a7633be72e07e50168307b5107a1bc3f5c10e9e07590ae4faca8dff47f582
        ports:
        - containerPort: 5000